# ubernim / CONSTANTS #
#---------------------#

import
  xam

use os,DirSep

const
  UNIM_EXTENSION* = ".unim"
  UNIM_PROJECT_EXTENSION* = ".unimp"
  UNIM_FILE_KEY* = "UNIM_FILE"
  UNIM_DESTINATION_KEY* = "UNIM_DESTINATION"
  DEFAULT_DIR* = STRINGS_PERIOD & DirSep
  UNIM_FLUSH_KEY* = "UNIM_FLUSH"
  FLAG_YES* = "yes" # default
  FLAG_NO* = "no"
  UNIM_MODE_KEY* = "UNIM_MODE"
  MODE_FREE* = "free" # default
  MODE_STRICT* = "strict"
  UNIM_CLEANUP_KEY* = "UNIM_CLEANUP"
  VALUE_IGNORED* = "ignored" # default
  VALUE_INFORMED* = "informed"
  VALUE_PERFORMED* = "performed"
  FREQ_IMPORTING_KEY* = "FREQ_IMPORTING"
  FREQ_EXPORTING_KEY* = "FREQ_EXPORTING"
  FREQUENCY_ALWAYS* = "always" # default
  FREQUENCY_ONCE* = "once"
  NIMC_DEFINES_KEY* = "NIMC_DEFINES"
  NIMC_SWITCHES_KEY* = "NIMC_SWITCHES"
  NIMC_CFGFILE_KEY* = "NIMC_CFGFILE"
  NIMC_PROJECT_KEY* = "NIMC_PROJECT"
  NIMC_TARGET_KEY* = "NIMC_TARGET"
  KEY_DIVISION* = "DIVISION"
  KEY_SUBDIVISION* = "SUBDIVISION"
  DIVISIONS_TARGETED* = "TARGETED"
  SUBDIVISIONS_TARGETED_PASS* = "TARGETED_PASS"
  SUBDIVISIONS_TARGETED_COMPILE* = "TARGETED_COMPILE"
  SUBDIVISIONS_TARGETED_LINK* = "TARGETED_LINK"
  SUBDIVISIONS_TARGETED_EMIT* = "TARGETED_EMIT"
  DIVISIONS_PROJECT* = "PROJECT"
  TO_COMPILER* = "to:compiler"
  TO_LOCAL* = "to:local"
  TO_LINKER* = "to:linker"
  PASS_COMPILER* = "passC"
  PASS_LOCAL* = "localPassC"
  PASS_LINK* = "passL"
  TARGET_CC* = "cc"
  TARGET_CPP* = "cpp"
  TARGET_OBJC* = "objc"
  TARGET_JS* = "js"
  NIMC_TARGETS* = [TARGET_CC, TARGET_CPP, TARGET_OBJC, TARGET_JS]
  NIMC_INVOKATION* = "nim"
  NIMC_DEFINE* = "--define:"
  COMMANDS_HELP* = "help"
  COMMANDS_DEFINE* = "define"
  COMMANDS_VERSION* = "version"
  NAMES_ITEM* = "item"
  NAMES_FIELD* = "field"
  NAMES_GETTER* = "getter"
  NAMES_SETTER* = "setter"
  NAMES_METHOD* = "method"
  NAMES_MEMBER* = "member"
  NAMES_SEALED* = "sealed"
  NAMES_PRAGMAS* = "pragmas"
  NAMES_ROUTINE* = "routine"
  NAMES_TEMPLATE* = "template"
  NAMES_CONSTRUCTOR* = "constructor"

let errors* = (
  UNEXPECTED: "errors.UNEXPECTED",
  BAD_STATE: "errors.BAD_STATE",
  OLD_VERSION: "errors.OLD_VERSION",
  BAD_VERSION: "errors.BAD_VERSION",
  BAD_FLAG: "errors.BAD_FLAG",
  BAD_MODE: "errors.BAD_MODE",
  BAD_FREQUENCY: "errors.BAD_FREQUENCY",
  BAD_CLEANUP: "errors.BAD_CLEANUP",
  BAD_TARGET: "errors.BAD_TARGET",
  STRICT_MODE: "errors.STRICT_MODE",
  ONLY_TOP_LEVEL: "errors.ONLY_TOP_LEVEL",
  DONT_TOP_LEVEL: "errors.DONT_TOP_LEVEL",
  CANT_BE_REQUIRED: "errors.CANT_BE_REQUIRED",
  NO_RECURSIVE_REQUIRE: "errors.NO_RECURSIVE_REQUIRE",
  NO_CIRCULAR_REFERENCE: "errors.NO_CIRCULAR_REFERENCE",
  INVALID_IDENTIFIER: "errors.INVALID_IDENTIFIER",
  UNDEFINED_REFERENCE: "errors.UNDEFINED_REFERENCE",
  ALREADY_DEFINED: "errors.ALREADY_DEFINED",
  NEVER_DEFINED: "errors.NEVER_DEFINED",
  WRONGLY_DEFINED: "errors.WRONGLY_DEFINED",
  CANT_HOLD_FIELDS: "errors.CANT_HOLD_FIELDS",
  CANT_HOLD_METHODS: "errors.CANT_HOLD_METHODS",
  CANT_HOLD_TEMPLATES: "errors.CANT_HOLD_TEMPLATES",
  CANT_HOLD_PRAGMAS: "errors.CANT_HOLD_PRAGMAS",
  CANT_HOLD_VALUE: "errors.CANT_HOLD_VALUE",
  CANT_OUTPUT_DOCS: "errors.CANT_OUTPUT_DOCS",
  CANT_OUTPUT_CODE: "errors.CANT_OUTPUT_CODE",
  MISSING_MEMBER: "errors.MISSING_MEMBER",
  UNDEFINED_MEMBER_VALUE: "errors.UNDEFINED_MEMBER_VALUE",
  DEFINE_BEFORE_VALUE: "errors.DEFINE_BEFORE_VALUE",
  ALREADY_RENDERED: "errors.ALREADY_RENDERED",
  NOT_APPLIABLE: "errors.NOT_APPLIABLE",
  ALREADY_APPLYING: "errors.ALREADY_APPLYING",
  ALREADY_EXTENDING: "errors.ALREADY_EXTENDING",
  CANT_EXTEND_INEXISTENT: "errors.CANT_EXTEND_INEXISTENT",
  CANT_EXTEND_DIFFERENT: "errors.CANT_EXTEND_DIFFERENT",
  CANT_EXTEND_SEALED: "errors.CANT_EXTEND_SEALED",
  RECORDS_CANT_EXTEND: "errors.RECORDS_CANT_EXTEND",
  RECORDS_DONT_ASTERISK: "errors.RECORDS_DONT_ASTERISK",
  VISIBILITY_DOESNT_MATCH: "errors.VISIBILITY_DOESNT_MATCH",
  NOT_IN_TARGETED: "errors.NOT_IN_TARGETED",
  NOT_IN_PROJECT: "errors.NOT_IN_PROJECT",
  CANT_CREATE_DIRECTORY: "errors.CANT_CREATE_DIRECTORY",
  CANT_APPEND_FILE: "errors.CANT_APPEND_FILE",
  CANT_WRITE_FILE: "errors.CANT_WRITE_FILE",
  CANT_REMOVE_FILE: "errors.CANT_REMOVE_FILE",
  FAILURE_PROCESSING: "errors.FAILURE_PROCESSING",
  CANT_WRITE_CONFIG: "errors.CANT_WRITE_CONFIG",
  CANT_WRITE_OUTPUT: "errors.CANT_WRITE_OUTPUT",
  MINIMUM_NIM_VERSION: "errors.MINIMUM_NIM_VERSION"
)
